name: gh-pages-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  gh-pages-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.x
        cache: 'npm'
    - name: Initializing ...
      run: npm install
    - name: Building ...
      run: |
        npm run build-lib
        npm run test
